name: Build Docker Images to Github Packages
on: [push]
jobs:
    build-api:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Publish API to Github Packages
          uses: elgohr/Publish-Docker-Github-Action@v5
          with:
            name: stlrda/redb-api/redb-api
            username: ${{ github.actor }}
            password: ${{ secrets.TOKEN }}
            registry: docker.pkg.github.com
